import{initializeApp as e}from"https://www.gstatic.com/firebasejs/10.7.1/firebase-app.js";import{getDatabase as t,ref as a,onValue as i,push as l,serverTimestamp as n}from"https://www.gstatic.com/firebasejs/10.7.1/firebase-database.js";let firebaseConfig={databaseURL:"https://movie-box-b4daf-default-rtdb.firebaseio.com"},app=e(firebaseConfig),db=t(app),adminAvatar="https://via.placeholder.com/36",allData=[],currentItem=null,settingsRef=a(db,"settings/adminAvatar");function checkUrlAndOpenModal(e){let t=new URLSearchParams(window.location.search),a=t.get("view");if(a){let i=decodeURIComponent(a).replace(/-/g," ").trim().toLowerCase(),l=e.find(e=>e.title.toLowerCase()===i);if(l){let n=timeAgo(l.timestamp);window.openModal(l,n,!1)}}}function timeAgo(e){if(!e)return"Recently";let t=Math.floor((Date.now()-e)/1e3);return t>86400?Math.floor(t/86400)+" days ago":t>3600?Math.floor(t/3600)+" hours ago":t>60?Math.floor(t/60)+" mins ago":"Just now"}function saveHistory(e){let t=JSON.parse(localStorage.getItem("hist"))||[];(t=t.filter(t=>t.id!==e.id)).unshift(e),localStorage.setItem("hist",JSON.stringify(t))}i(settingsRef,e=>{let t=e.val();t&&(adminAvatar=t,document.querySelectorAll(".channel-icon").forEach(e=>{e.src=adminAvatar}))}),i(a(db,"prompts/"),e=>{let t=e.val();allData=[],t?(Object.keys(t).forEach(e=>allData.push({id:e,...t[e]})),allData.reverse(),window.renderGrid(allData,"contentGrid"),window.renderGrid(allData.filter(e=>parseFloat(e.rating)>=4.5),"trendingGrid"),checkUrlAndOpenModal(allData)):document.getElementById("contentGrid").innerHTML="<p style='text-align:center'>No Data</p>"}),window.renderGrid=(e,t)=>{let a=document.getElementById(t);a.innerHTML="",e.forEach(e=>{let t=timeAgo(e.timestamp),i=document.createElement("div");i.className="card",i.onclick=()=>window.openModal(e,t,!0),i.innerHTML=`
            <div class="thumbnail-container">
                <img src="${e.imgLink}" class="card-img" onerror="this.src='https://via.placeholder.com/480x270'">
            </div>
            <div class="card-meta">
                <img src="${adminAvatar}" class="channel-icon">
                <div class="text-info">
                    <div class="card-title">${e.title}</div>
                    <div class="card-subtitle">Rating: ${e.rating} • ${t}</div>
                </div>
            </div>
        `,a.appendChild(i)})},window.openModal=(e,t,a=!0)=>{currentItem=e,document.getElementById("modalImg").src=e.imgLink,document.getElementById("modalTitle").innerText=e.title,document.getElementById("modalPrompt").innerText=e.prompt,document.getElementById("modalMeta").innerText=`Posted: ${t} • Rating: ${e.rating}`;let i=e.title.trim().replace(/\s+/g,"-"),l=`?view=${encodeURIComponent(i)}`;a&&window.history.pushState({modalOpen:!0,itemId:e.id},"",l);let n=document.getElementById("modalComments");n.innerHTML="",e.comments?Object.values(e.comments).forEach(e=>{n.innerHTML+=`<div style="border-bottom:1px dashed var(--border-color); padding:5px 0; margin-bottom:5px;">
                <span style="color:var(--accent-color); font-weight:bold;">Visitor:</span> ${e.text}
            </div>`}):n.innerHTML="<p>No comments.</p>",document.getElementById("detailModal").style.display="block",saveHistory(e)},window.closeModal=()=>{window.location.search.includes("view=")?window.history.back():document.getElementById("detailModal").style.display="none"},window.onpopstate=e=>{document.getElementById("detailModal").style.display="none"},window.copyPrompt=()=>{navigator.clipboard.writeText(document.getElementById("modalPrompt").innerText),alert("Copied!")},window.shareItem=async()=>{if(!currentItem)return;let e={title:currentItem.title,text:`Check this AI Art!
${currentItem.title}
${window.location.href}`,url:window.location.href};try{await navigator.share(e)}catch{alert("Link copied!"),navigator.clipboard.writeText(e.text)}},document.getElementById("postComment").addEventListener("click",()=>{let e=document.getElementById("commentInput").value;currentItem&&e&&(l(a(db,`prompts/${currentItem.id}/comments`),{text:e,timestamp:n()}),document.getElementById("commentInput").value="")}),window.openThemeSelector=()=>document.getElementById("themeModal").classList.add("active"),window.closeThemeSelector=()=>document.getElementById("themeModal").classList.remove("active"),window.setTheme=e=>{document.body.className=e,localStorage.setItem("theme",e),closeThemeSelector()},document.body.className=localStorage.getItem("theme")||"theme-gradient",window.openHistoryPage=()=>{window.showPage("historyPage"),window.renderGrid(JSON.parse(localStorage.getItem("hist"))||[],"historyGrid")},window.shareApp=()=>{navigator.clipboard.writeText(window.location.href),alert("App Link Copied!")},window.switchTab=(e,t)=>{document.querySelectorAll(".page").forEach(e=>e.classList.remove("active")),document.getElementById(e).classList.add("active"),document.querySelectorAll(".nav-item").forEach(e=>e.classList.remove("active")),t.classList.add("active")},window.showPage
